<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKhsxbVN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKhsxbVN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKhsxbVN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKhsxbVN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKhsxbVN\App_KernelDevDebugContainer([
    'container.build_hash' => 'KhsxbVN',
    'container.build_id' => '9a737911',
    'container.build_time' => 1649704605,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKhsxbVN');
